CREATE TABLE aposta
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    comprovante character varying(36) NOT NULL,
    email character varying(64) NOT NULL,
    numero BIGINT NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL,

    PRIMARY KEY (id)
);
